import { IProduct } from "@/shared/types";

export const mockProducts: IProduct[] = [
  {
    id: 1,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },
  {
    id: 2,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 30.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 4,
    reviewCount: 10,
  },
  {
    id: 3,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/2.png",
    rating: 5,
    reviewCount: 10,
  },
  {
    id: 4,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },
  {
    id: 5,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/2.png",
    rating: 1,
    reviewCount: 110,
  },
  {
    id: 6,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },
  {
    id: 7,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },
  {
    id: 8,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },

  {
    id: 9,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },
  {
    id: 10,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },
  {
    id: 11,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },
  {
    id: 12,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },
  {
    id: 13,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },
  {
    id: 14,
    name: "Matte Cream SPF 20",
    description: "Day cream with mattifying effect",
    categoryId: 1,
    productBundleId: 1,
    discountPrice: 24.0,
    price: 48.0,
    stockQuantity: 10,
    imageUrl: "/images/products-mock/1.png",
    rating: 5,
    reviewCount: 10,
  },
];
